language: bash
services: docker

env:
  - VERSION=4.0 VARIANT=alpine3.9
  - VERSION=3.4 VARIANT=alpine3.9
  - VERSION=3.3 VARIANT=alpine3.9
  - VERSION=3.2 VARIANT=alpine3.9
  - VERSION=4.0 VARIANT=alpine3.8
  - VERSION=3.4 VARIANT=alpine3.8
  - VERSION=3.3 VARIANT=alpine3.8
  - VERSION=3.2 VARIANT=alpine3.8
  - VERSION=4.0 VARIANT=alpine3.7
  - VERSION=3.4 VARIANT=alpine3.7
  - VERSION=3.3 VARIANT=alpine3.7
  - VERSION=3.2 VARIANT=alpine3.7
  - VERSION=4.0 VARIANT=alpine3.6
  - VERSION=3.4 VARIANT=alpine3.6
  - VERSION=3.3 VARIANT=alpine3.6
  - VERSION=3.2 VARIANT=alpine3.6
  - VERSION=4.0 VARIANT=stretch
  - VERSION=3.4 VARIANT=stretch
  - VERSION=3.3 VARIANT=stretch
  - VERSION=3.2 VARIANT=stretch
  - VERSION=3.1 VARIANT=stretch
  - VERSION=4.0 VARIANT=jessie
  - VERSION=3.4 VARIANT=jessie
  - VERSION=3.3 VARIANT=jessie
  - VERSION=3.2 VARIANT=jessie
  - VERSION=3.1 VARIANT=jessie

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="haxe:$(awk '$1 == "ENV" && $2 == "HAXE_VERSION" { print $3; exit }' ${VARIANT:+$VARIANT}/Dockerfile)"

script:
  - docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
