jobs:
  - job: TestLinux
    pool:
      vmImage: 'ubuntu-20.04'
    strategy:
      matrix:
        haxe4.2-alpine3.17: { VERSION: 4.2, VARIANT: alpine3.17 }
        haxe4.1-alpine3.17: { VERSION: 4.1, VARIANT: alpine3.17 }
        haxe4.0-alpine3.17: { VERSION: 4.0, VARIANT: alpine3.17 }
        haxe4.2-alpine3.16: { VERSION: 4.2, VARIANT: alpine3.16 }
        haxe4.1-alpine3.16: { VERSION: 4.1, VARIANT: alpine3.16 }
        haxe4.0-alpine3.16: { VERSION: 4.0, VARIANT: alpine3.16 }
        haxe4.2-alpine3.15: { VERSION: 4.2, VARIANT: alpine3.15 }
        haxe4.1-alpine3.15: { VERSION: 4.1, VARIANT: alpine3.15 }
        haxe4.0-alpine3.15: { VERSION: 4.0, VARIANT: alpine3.15 }
        haxe4.2-alpine3.14: { VERSION: 4.2, VARIANT: alpine3.14 }
        haxe4.1-alpine3.14: { VERSION: 4.1, VARIANT: alpine3.14 }
        haxe4.0-alpine3.14: { VERSION: 4.0, VARIANT: alpine3.14 }
        haxe4.2-bullseye: { VERSION: 4.2, VARIANT: bullseye }
        haxe4.1-bullseye: { VERSION: 4.1, VARIANT: bullseye }
        haxe4.0-bullseye: { VERSION: 4.0, VARIANT: bullseye }
        haxe4.2-buster: { VERSION: 4.2, VARIANT: buster }
        haxe4.1-buster: { VERSION: 4.1, VARIANT: buster }
        haxe4.0-buster: { VERSION: 4.0, VARIANT: buster }
        haxe3.4-buster: { VERSION: 3.4, VARIANT: buster }
        haxe3.3-buster: { VERSION: 3.3, VARIANT: buster }
        haxe3.2-buster: { VERSION: 3.2, VARIANT: buster }
    steps:
      - template: azure-pipelines-steps.yml
      - bash: docker run --rm "${IMAGE}" haxe -version 2>&1 | grep "$VERSION"
        displayName: Test haxe
      - bash: git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images
        displayName: Clone docker-library/official-images
      - bash: ~/official-images/test/run.sh "${IMAGE}"
        displayName: Test image
  - job: TestWindows
    strategy:
      matrix:
        # ltsc2022
        haxe4.2-windowsservercore-ltsc2022: { VMIMAGE: 'windows-2022', VERSION: 4.2, VARIANT: windowsservercore-ltsc2022 }
        haxe4.1-windowsservercore-ltsc2022: { VMIMAGE: 'windows-2022', VERSION: 4.1, VARIANT: windowsservercore-ltsc2022 }
        haxe4.0-windowsservercore-ltsc2022: { VMIMAGE: 'windows-2022', VERSION: 4.0, VARIANT: windowsservercore-ltsc2022 }
        haxe3.4-windowsservercore-ltsc2022: { VMIMAGE: 'windows-2022', VERSION: 3.4, VARIANT: windowsservercore-ltsc2022 }
        haxe3.3-windowsservercore-ltsc2022: { VMIMAGE: 'windows-2022', VERSION: 3.3, VARIANT: windowsservercore-ltsc2022 }
        haxe3.2-windowsservercore-ltsc2022: { VMIMAGE: 'windows-2022', VERSION: 3.2, VARIANT: windowsservercore-ltsc2022 }
        haxe3.1-windowsservercore-ltsc2022: { VMIMAGE: 'windows-2022', VERSION: 3.1, VARIANT: windowsservercore-ltsc2022 }
        # 1809
        haxe4.2-windowsservercore-1809: { VMIMAGE: 'windows-2019', VERSION: 4.2, VARIANT: windowsservercore-1809 }
        haxe4.1-windowsservercore-1809: { VMIMAGE: 'windows-2019', VERSION: 4.1, VARIANT: windowsservercore-1809 }
        haxe4.0-windowsservercore-1809: { VMIMAGE: 'windows-2019', VERSION: 4.0, VARIANT: windowsservercore-1809 }
        haxe3.4-windowsservercore-1809: { VMIMAGE: 'windows-2019', VERSION: 3.4, VARIANT: windowsservercore-1809 }
        haxe3.3-windowsservercore-1809: { VMIMAGE: 'windows-2019', VERSION: 3.3, VARIANT: windowsservercore-1809 }
        haxe3.2-windowsservercore-1809: { VMIMAGE: 'windows-2019', VERSION: 3.2, VARIANT: windowsservercore-1809 }
        haxe3.1-windowsservercore-1809: { VMIMAGE: 'windows-2019', VERSION: 3.1, VARIANT: windowsservercore-1809 }
    pool:
      vmImage: $(VMIMAGE)
    steps:
      - template: azure-pipelines-steps.yml
      - bash: docker run --rm "${IMAGE}" haxe -version 2>&1 | grep "$VERSION"
        displayName: Test haxe
      - bash: docker run --rm "${IMAGE}" haxelib install jQueryExtern
        displayName: Test haxelib
