steps:
  - bash: |
      IMAGE="haxe:$(awk '$1 == "ENV" && $2 == "HAXE_VERSION" { print $3; exit }' ${VARIANT:+$VARIANT}/Dockerfile)"
      echo "$IMAGE"
      echo "##vso[task.setvariable variable=IMAGE]$IMAGE"
    workingDirectory: $(VERSION)
    displayName: Define image name
  - bash: docker build --pull -t "${IMAGE}" "$(VERSION)/${VARIANT:-.}"
    displayName: Build image
  - bash: docker images
    displayName: List images
