jobs:
  - job: TestLinux
    pool:
      vmImage: 'ubuntu-20.04'
    strategy:
      matrix:
        haxe4.2-alpine3.15: { VERSION: 4.2, VARIANT: alpine3.15 }
        haxe4.1-alpine3.15: { VERSION: 4.1, VARIANT: alpine3.15 }
        haxe4.0-alpine3.15: { VERSION: 4.0, VARIANT: alpine3.15 }
        haxe4.2-alpine3.14: { VERSION: 4.2, VARIANT: alpine3.14 }
        haxe4.1-alpine3.14: { VERSION: 4.1, VARIANT: alpine3.14 }
        haxe4.0-alpine3.14: { VERSION: 4.0, VARIANT: alpine3.14 }
        haxe4.2-alpine3.13: { VERSION: 4.2, VARIANT: alpine3.13 }
        haxe4.1-alpine3.13: { VERSION: 4.1, VARIANT: alpine3.13 }
        haxe4.0-alpine3.13: { VERSION: 4.0, VARIANT: alpine3.13 }
        haxe3.4-alpine3.13: { VERSION: 3.4, VARIANT: alpine3.13 }
        haxe3.3-alpine3.13: { VERSION: 3.3, VARIANT: alpine3.13 }
        haxe3.2-alpine3.13: { VERSION: 3.2, VARIANT: alpine3.13 }
        haxe4.2-alpine3.12: { VERSION: 4.2, VARIANT: alpine3.12 }
        haxe4.1-alpine3.12: { VERSION: 4.1, VARIANT: alpine3.12 }
        haxe4.0-alpine3.12: { VERSION: 4.0, VARIANT: alpine3.12 }
        haxe3.4-alpine3.12: { VERSION: 3.4, VARIANT: alpine3.12 }
        haxe3.3-alpine3.12: { VERSION: 3.3, VARIANT: alpine3.12 }
        haxe3.2-alpine3.12: { VERSION: 3.2, VARIANT: alpine3.12 }
        haxe4.2-bullseye: { VERSION: 4.2, VARIANT: bullseye }
        haxe4.1-bullseye: { VERSION: 4.1, VARIANT: bullseye }
        haxe4.0-bullseye: { VERSION: 4.0, VARIANT: bullseye }
        haxe4.2-buster: { VERSION: 4.2, VARIANT: buster }
        haxe4.1-buster: { VERSION: 4.1, VARIANT: buster }
        haxe4.0-buster: { VERSION: 4.0, VARIANT: buster }
        haxe3.4-buster: { VERSION: 3.4, VARIANT: buster }
        haxe3.3-buster: { VERSION: 3.3, VARIANT: buster }
        haxe3.2-buster: { VERSION: 3.2, VARIANT: buster }
        haxe4.0-stretch: { VERSION: 4.0, VARIANT: stretch }
        haxe3.4-stretch: { VERSION: 3.4, VARIANT: stretch }
        haxe3.3-stretch: { VERSION: 3.3, VARIANT: stretch }
        haxe3.2-stretch: { VERSION: 3.2, VARIANT: stretch }
        haxe3.1-stretch: { VERSION: 3.1, VARIANT: stretch }
    steps:
      - template: azure-pipelines-steps.yml
      - bash: docker run --rm "${IMAGE}" haxe -version | grep "$VERSION"
        displayName: Test haxe
      - bash: git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images
        displayName: Clone docker-library/official-images
      - bash: ~/official-images/test/run.sh "${IMAGE}"
        displayName: Test image
  - job: TestWin1809
    pool:
      vmImage: 'windows-2019'
    strategy:
      matrix:
        haxe4.2-windowsservercore-1809: { VERSION: 4.2, VARIANT: windowsservercore-1809 }
        haxe4.1-windowsservercore-1809: { VERSION: 4.1, VARIANT: windowsservercore-1809 }
        haxe4.0-windowsservercore-1809: { VERSION: 4.0, VARIANT: windowsservercore-1809 }
        haxe3.4-windowsservercore-1809: { VERSION: 3.4, VARIANT: windowsservercore-1809 }
        haxe3.3-windowsservercore-1809: { VERSION: 3.3, VARIANT: windowsservercore-1809 }
        haxe3.2-windowsservercore-1809: { VERSION: 3.2, VARIANT: windowsservercore-1809 }
        haxe3.1-windowsservercore-1809: { VERSION: 3.1, VARIANT: windowsservercore-1809 }
    steps:
      - template: azure-pipelines-steps.yml
      - bash: docker run --rm "${IMAGE}" haxe -version | grep "$VERSION"
        displayName: Test haxe
      - bash: docker run --rm "${IMAGE}" haxelib install jQueryExtern
        displayName: Test haxelib
