jobs:
  - job: TestLinux
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        haxe4.0-alpine3.10: { VERSION: 4.0, VARIANT: alpine3.10 }
        haxe3.4-alpine3.10: { VERSION: 3.4, VARIANT: alpine3.10 }
        haxe3.3-alpine3.10: { VERSION: 3.3, VARIANT: alpine3.10 }
        haxe3.2-alpine3.10: { VERSION: 3.2, VARIANT: alpine3.10 }
        haxe4.0-alpine3.9: { VERSION: 4.0, VARIANT: alpine3.9 }
        haxe3.4-alpine3.9: { VERSION: 3.4, VARIANT: alpine3.9 }
        haxe3.3-alpine3.9: { VERSION: 3.3, VARIANT: alpine3.9 }
        haxe3.2-alpine3.9: { VERSION: 3.2, VARIANT: alpine3.9 }
        haxe4.0-alpine3.8: { VERSION: 4.0, VARIANT: alpine3.8 }
        haxe3.4-alpine3.8: { VERSION: 3.4, VARIANT: alpine3.8 }
        haxe3.3-alpine3.8: { VERSION: 3.3, VARIANT: alpine3.8 }
        haxe3.2-alpine3.8: { VERSION: 3.2, VARIANT: alpine3.8 }
        haxe4.0-alpine3.7: { VERSION: 4.0, VARIANT: alpine3.7 }
        haxe3.4-alpine3.7: { VERSION: 3.4, VARIANT: alpine3.7 }
        haxe3.3-alpine3.7: { VERSION: 3.3, VARIANT: alpine3.7 }
        haxe3.2-alpine3.7: { VERSION: 3.2, VARIANT: alpine3.7 }
        haxe4.0-buster: { VERSION: 4.0, VARIANT: buster }
        haxe3.4-buster: { VERSION: 3.4, VARIANT: buster }
        haxe3.3-buster: { VERSION: 3.3, VARIANT: buster }
        haxe3.2-buster: { VERSION: 3.2, VARIANT: buster }
        haxe4.0-stretch: { VERSION: 4.0, VARIANT: stretch }
        haxe3.4-stretch: { VERSION: 3.4, VARIANT: stretch }
        haxe3.3-stretch: { VERSION: 3.3, VARIANT: stretch }
        haxe3.2-stretch: { VERSION: 3.2, VARIANT: stretch }
        haxe3.1-stretch: { VERSION: 3.1, VARIANT: stretch }
        haxe4.0-jessie: { VERSION: 4.0, VARIANT: jessie }
        haxe3.4-jessie: { VERSION: 3.4, VARIANT: jessie }
        haxe3.3-jessie: { VERSION: 3.3, VARIANT: jessie }
        haxe3.2-jessie: { VERSION: 3.2, VARIANT: jessie }
        haxe3.1-jessie: { VERSION: 3.1, VARIANT: jessie }
    steps:
      - template: azure-pipelines-steps.yml
      - bash: git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images
        displayName: Clone docker-library/official-images
      - bash: ~/official-images/test/run.sh "${IMAGE}"
        displayName: Test image
  - job: TestWin1809
    pool:
      vmImage: 'windows-2019'
    strategy:
      matrix:
        haxe4.0-windowsservercore-1809: { VERSION: 4.0, VARIANT: windowsservercore-1809 }
        haxe3.4-windowsservercore-1809: { VERSION: 3.4, VARIANT: windowsservercore-1809 }
        haxe3.3-windowsservercore-1809: { VERSION: 3.3, VARIANT: windowsservercore-1809 }
        haxe3.2-windowsservercore-1809: { VERSION: 3.2, VARIANT: windowsservercore-1809 }
        haxe3.1-windowsservercore-1809: { VERSION: 3.1, VARIANT: windowsservercore-1809 }
    steps:
      - template: azure-pipelines-steps.yml
      - bash: docker run --rm "${IMAGE}" haxe -version
        displayName: Test haxe
      - bash: docker run --rm "${IMAGE}" haxelib install jQueryExtern
        displayName: Test haxelib
  - job: TestWin1803
    pool:
      vmImage: 'win1803'
    strategy:
      matrix:
        haxe4.0-windowsservercore-1803: { VERSION: 4.0, VARIANT: windowsservercore-1803 }
        haxe3.4-windowsservercore-1803: { VERSION: 3.4, VARIANT: windowsservercore-1803 }
        haxe3.3-windowsservercore-1803: { VERSION: 3.3, VARIANT: windowsservercore-1803 }
        haxe3.2-windowsservercore-1803: { VERSION: 3.2, VARIANT: windowsservercore-1803 }
        haxe3.1-windowsservercore-1803: { VERSION: 3.1, VARIANT: windowsservercore-1803 }
    steps:
      - template: azure-pipelines-steps.yml
      - bash: docker run --rm "${IMAGE}" haxe -version
        displayName: Test haxe
      - bash: docker run --rm "${IMAGE}" haxelib install jQueryExtern
        displayName: Test haxelib
