steps:
  - bash: |
      IMAGE="haxe:$(grep -oP '(?<=ENV HAXE_VERSION[=\s]).+' ${VARIANT:+$VARIANT}/Dockerfile)"
      echo "$IMAGE"
      echo "##vso[task.setvariable variable=IMAGE]$IMAGE"
    workingDirectory: $(VERSION)
    displayName: Define image name
  - bash: docker build --pull -t "${IMAGE}" "$(VERSION)/${VARIANT:-.}"
    displayName: Build image
  - bash: docker images
    displayName: List images
