::HEADER::

FROM haxe:::HAXE_VERSION::

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# install dependencies
ONBUILD COPY *.hxml /usr/src/app/
ONBUILD RUN yes | haxelib install all

# compile the project
ONBUILD COPY . /usr/src/app
ONBUILD ARG BUILD_HXML=build.hxml
ONBUILD RUN haxe $BUILD_HXML